### ISSUE TITLE
Update function is not working

### ISSUE THREAD

**Issue by realM4C** [migliori/php-pdo-db-class#1]
This will drop "PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string" if a where clause is defined....
https://github.com/migliori/php-pdo-db-class/blob/159785740799b7c896f028de34b957af1e27449a/src/Db.php#L880C19-L880C24

**Comment by migliori** [comment]
Hi,

I fixed it, but please this project is deprecated, you should use [https://github.com/migliori/power-lite-pdo instead](https://github.com/migliori/power-lite-pdo instead)
